### ISSUE TITLE
NumberField fails when number is bigger than int max

### ISSUE THREAD

**Issue by Tharnas** [tomasmcguinness/dotnet-passbook#120]
When providing in a field a number which is bigger than 2147483647 (int.MaxValue) an overflow exception is raised:

"Value was either too large or too small for an Int32."

Stacktrace
   _at System.Decimal.ToInt32(Decimal d)
   at System.Decimal.op_Explicit(Decimal value)
   at Passbook.Generator.Fields.NumberField.WriteValue(JsonWriter writer)
   at Passbook.Generator.Fields.Field.Write(JsonWriter writer)
   at Passbook.Generator.PassGeneratorRequest.WriteSection(JsonWriter writer, String sectionName, List`1 fields)
   at Passbook.Generator.PassGeneratorRequest.Write(JsonWriter writer)
   at Passbook.Generator.PassGenerator.CreatePassFile(PassGeneratorRequest request)
   at Passbook.Generator.PassGenerator.CreatePackage(PassGeneratorRequest request)
   at Passbook.Generator.PassGenerator.Generate(PassGeneratorRequest request)_

The problem is that casting a number bigger than int.MaxValue will cause this exception:
[https://github.com/tomasmcguinness/dotnet-passbook/blob/6240c2c72a7d52ffbab138798831d0355ce34cf2/Passbook.Generator/Fields/NumberField.cs#L51](https://github.com/tomasmcguinness/dotnet-passbook/blob/6240c2c72a7d52ffbab138798831d0355ce34cf2/Passbook.Generator/Fields/NumberField.cs#L51)

**Comment by tomasmcguinness** [comment]
If you find this library useful, please consider sponsoring the project - you can hit the Sponsor button at the top of the page or visit https://ko-fi.com/tomasmcguinness - thanks!
