### ISSUE TITLE
dotnet Core 2.0?

### ISSUE THREAD

**Issue by PunkStarStudios** [tomasmcguinness/dotnet-passbook#59]
I'm trying to implement a server web api using .net core 2.0
At the 
byte[] generatedPass = generator.Generate(request);
line I get the following error (I have a feeling it's a dot net core issue) :
 
System.TypeLoadException
  HResult=0x80131522
  Message=Could not load type 'System.Security.Cryptography.Pkcs.SignedCms' from assembly 'System.Security, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
  Source=Passbook.Generator
  StackTrace:
   at Passbook.Generator.PassGenerator.SignManifestFile(PassGeneratorRequest request)
   at Passbook.Generator.PassGenerator.GenerateManifestFile(PassGeneratorRequest request)
   at Passbook.Generator.PassGenerator.Generate(PassGeneratorRequest request)
   at PasskitServer.Controllers.PassesController.Get(String PassTypeId, String serialNo) in C:\Users\punky\Documents\Visual Studio 2017\Projects\PasskitServer\PasskitServer\Controllers\PassesController.cs:line 72
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()

**Comment by tomasmcguinness** [comment]
Hello,

I haven't tested dotnet-passbook on .Net Core, but I suggest trying to update this Nuget package as it might now support .Net Standard 2.0.

**Comment by PunkStarStudios** [comment]
Thanks.
I’ve abandoned core and just went straight into .net because there was one key method missing from core…

System.Security.Cryptography.pkcs.SignedCms does not exist in the core framework.
Ugh.
That one little thing was missing.
Perhaps there’s an equivalent BouncyCastle method … dunno…. but I decided to stop fighting and move on.

David Brewster
Developer
Howell Data Systems Inc.
Office: 905-761-1712 ext. 2133
www.howelldatasystems.com
Proudly serving great customers for 26 years!

**Comment by tomasmcguinness** [comment]
Okay, once you've making progress.
